### ISSUE TITLE
translation does not take effect

### ISSUE THREAD

**Issue by cmhello** [code-atlantic/content-control#1]
Thanks for your great work! 

I had a try for it and translated it into Chinese today. but I found the translation does not take effect. 

There is an error:

The 195 line:

`load_plugin_textdomain( 'content-control' );`

Should be changed to:

`load_plugin_textdomain( 'content-control', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/' );`

In addition, it is recommended to use wp_localize_script() function to make the text inside .js can be translated.

You can get Simplified Chinese language pack from  img.wpdaxue.com/2016/10/content-control-zh_CN.zip

---

BTW, Could you make it be compatible with Woocommerce and Easy Digital Downloads, only buy one or more of the specified goods in order to view the content...

Thanks again!

**Comment by danieliser** [comment]
@cmhello Sorry for the delay, never saw this issue. The plugins languages are loaded via wordpress.org langpacks. Translating it via https://translate.wordpress.org/projects/wp-plugins/content-control.

This way the language is auto loaded when available, no need to manage mo files in the plugin any longer. That is why we only use the first parameter in `load_text_domain`

We are looking to add several other conditions for direct integration with top plugins. Can't say yet whether they will be all free or if we will try to monetize this with a pro version at some point.

Adding your conditions ideas ad seperate features though.
