### ISSUE TITLE
Custom URL field shows when editing restriction with "Custom Message"

### ISSUE THREAD

**Issue by fpcorso** [code-atlantic/content-control#10]
When editing a restriction with a "custom message", the "custom URL" field shows.

Steps to reproduce:

* Add new restriction
* Set who can see this content to "Logged In Users".
* Set "Choose how to protect your content" to "Custom Message" and leave other options on "Protection" tab unchecked.
* Save restriction rule.
* Go back to restriction rules (or refresh page)
* Edit new rule and view "Protection" tab.

You will see the drop down set to "Custom Message" but the "Custom URL" field will be shown which is confusing.

**Comment by danieliser** [comment]
Unable to duplicate in the current build.
