### ISSUE TITLE
Broken Link In Popup

### ISSUE THREAD

**Issue by gangradem** [code-atlantic/content-control#103]
I found a tiny bug in the Content Control plugin.
The Get Started link in this popup redirects to [contentcontrolpro.com](http://contentcontrolpro.com/):

![image](https://github.com/code-atlantic/content-control/assets/84750225/f45f4bd6-0e16-485a-b64e-3aa51d277e3b)

But I see this error on that domain:

![image](https://github.com/code-atlantic/content-control/assets/84750225/415dbe6d-5d89-4314-a494-33332a8e578e)

I think this URL needs to be updated to the new site.

This popup shows up when you try to add a conditional rule to any block in the Gutenberg editor.

**Comment by danieliser** [comment]
Fixed thanks
