### ISSUE TITLE
2.3.0 problems with Polylang

### ISSUE THREAD

**Issue by DavidOtero91** [code-atlantic/content-control#107]
Hello,

I'm reporting an issue with version 2.3.0. When Polylang is installed, there seem to be infinite loop problems. I haven't been able to investigate this thoroughly yet, but it's worth noting that this doesn't occur with version 2.8.0. Additionally, Elementor is also installed on the site.

Regards

**Comment by danieliser** [comment]
Fix from Polylang team has been merged, we will push it out shortly.
