### ISSUE TITLE
Logged out attribute on shortcode appears broken

### ISSUE THREAD

**Issue by fpcorso** [code-atlantic/content-control#11]
If you edit a post and add this shortcode:

[content_control logged_out]This is an example of content you need to be logged out to see![/content_control]

This will have the content shown to logged-in users as well when it should only be shown to logged out users.

**Comment by danieliser** [comment]
@fpcorso can't duplicate this one. That shortcode as is shows nothing for logged in user and shows the sentence when logged out.

Can you test with the latest version?

**Comment by fpcorso** [comment]
@danieliser This is sort of working now. However, should it show the denial message or should it be blank? If it should show the denial message, maybe we should have a separate default message for the logged_out attribute?

Using it here:
![image](https://user-images.githubusercontent.com/9730040/68689084-d7ce8000-053d-11ea-96f1-3badd5ea186c.png)

Results in seeing this when logged out, which is correct:
![image](https://user-images.githubusercontent.com/9730040/68689240-0c423c00-053e-11ea-8b8a-d6216669ed6d.png)

When logged in, I see the denial message telling me that I need to be logged in, which doesn't make sense. But, I wouldn't change the denial message as I would want it to tell people they need to be logged-in in most other cases:
![image](https://user-images.githubusercontent.com/9730040/68689372-3ac01700-053e-11ea-921b-201ceac16b9a.png)

**Comment by danieliser** [comment]
@fpcorso So currently its showing a denial message? For me it showed nothing I thought.

I think it should technically be capable of both, as well as a custom message if denied per shortcode.

So maybe should be

`[content control logged_out] Sign Up Now [/content_control]`

`[content control logged_in denial_message="Log in to view this content"] You are logged in [/content_control]`

If so we should probably write up a new issue.

**Comment by fpcorso** [comment]
Yeah @danieliser, it was showing the default denial message when using logged_out which made it confusing. If that is how it is currently supposed to work, we can close this out as the bug is fixed and then start discussing ways to improve that workflow in a different issue.

**Comment by danieliser** [comment]
Yea I think it may pull from the global settings now. Probably close this one and start proposing improvements.
