### ISSUE TITLE
Pages/Categories do not persist after updating rule

### ISSUE THREAD

**Issue by noctividus** [code-atlantic/content-control#17]
Steps:
1. I add a rule.
2. Setup General and Protection tabs.
3. Setup Content tab as shown:
![image](https://user-images.githubusercontent.com/5158351/71774753-00b13700-2f29-11ea-94d1-74066cdf9b94.png)

4. Add a few pages and a few categories.
5. Click update.
6. Return to edit, and all the pages and categories are gone:
![image](https://user-images.githubusercontent.com/5158351/71774736-de1f1e00-2f28-11ea-80ab-16d426904009.png)

**Comment by danieliser** [comment]
@noctividus Thanks for the report. This should already be patched in the dev branch and will be in the next release: https://github.com/JunglePlugins/Content-Control/commit/0e0036cbb7fe131b3ae7b7a8563a8c164f2e2b2d

If you can test that branch let us know. Solved it for us.
