### ISSUE TITLE
restriction not being saved; redirected to settings page upon save

### ISSUE THREAD

**Issue by gitnanji** [code-atlantic/content-control#22]
am trying to add rule to restrict users from not seeing posts of a particular category if they are not admins/editors but the rule never gets added, i keep getting redirected back to settings page upon adding the rule.

Have uploaded a screencast to show the issue here: https://imgur.com/a/sZG0gD8

![](https://i.imgur.com/UpkhGmy.mp4)

**Comment by danieliser** [comment]
@gitnanji - Can you check for JavaScript errors on the page: https://docs.wppopupmaker.com/article/373-checking-javascript-errors

Let us know.

**Comment by gitnanji** [comment]
I see a console error for `ReferenceError: tinyMCE is not defined`

**Comment by gitnanji** [comment]
can you tell me which exact line in the page's client side code is supposed to send the the data?

>Can you both check to see if there are any JavaScript errors on that page before or during submission? That is the only possible cause currently. We save using AJAX, it seems if that was disabled due to an error it could cause this type of thing.

If I knew exactly which line was triggering the ajax, I can add a debug point there and check.

**Comment by danieliser** [comment]
@gitnanji - Sure thing: https://github.com/JunglePlugins/Content-Control/blob/master/assets/scripts/settings-page.js#L7568

**Comment by gitnanji** [comment]
that piece of code doesn't seem to be doing anything upon success or failure.

anyway, is there any other information I can give you to help fix this issue? are you able to reproduce this issue on your setup?

**Comment by gitnanji** [comment]
did you get a chance to look at this issue @danieliser ?

**Comment by francescolofranco-dev** [comment]
Hi, I am having the exact same issue here `ReferenceError: tinyMCE is not defined` - Any update or reason why the issue has been closed? Was it resolved?

**Comment by danieliser** [comment]
This doesn't really appear to be a bug in our code we can fix. We enqueue the editor scripts, but sometimes 3rd party plugins deload them or cause it to not load etc.

Couple google searches turned up some possible solutions:
- https://www.creativetweets.com/how-to-solve-error-tinymce-is-not-defined-on-wordpress-admin-panel/
- https://siteorigin.com/thread/uncaught-referenceerror-tinymce-is-not-defined/
- https://wpml.org/forums/topic/uncaught-referenceerror-tinymce-is-not-defined-translation-editor-issues/
- https://toolset.com/forums/topic/tinymce-is-not-defined/

Solutions ranging from memory adjustments to disabling JS file concatenation.

**Comment by sfburton** [comment]
I understand that this is not a bug in the code. I just wanted to report that I am having the same issue.

**Comment by danieliser** [comment]
@sfburton - It may be that we are moving away from tinyMCE editor in general as we move to integrating with Gutenberg this year. Restrictions might be created using the block editor entirely for example.

That said did you read over the links above, did anything help?

**Comment by danieliser** [comment]
V2 is about to be released, this entire thread is no longer relevant as all functions in question have been rewritten from ground up using newer technologies.
