### ISSUE TITLE
Missing <p> when excerpt is shown above custom message on posts

### ISSUE THREAD

**Issue by fpcorso** [code-atlantic/content-control#30]
When setting up a rule that restricts a post to logged in users and shows a custom message, it appears as expected:
![image](https://user-images.githubusercontent.com/9730040/90780421-583fbf80-e2cc-11ea-8a9e-7aa1803fec79.png)

However, if you select to show the excerpt above message, it appears incorrect:
![image](https://user-images.githubusercontent.com/9730040/90780893-79a0ab80-e2cc-11ea-87cc-db274e5751f1.png)

Upon inspection, the first example has the message inside a `<p>` element while the second does not.

**Comment by danieliser** [comment]
Can't duplicate, text is rendered with <p> tags currently in all modes I tested.
