### ISSUE TITLE
Restriction Editor in Content Control not allowing to add a second 'Selected Page'

### ISSUE THREAD

**Issue by KenHook** [code-atlantic/content-control#34]
Hi. I'm using the Content Creator plug-in on a premium WP site with v5.5.3.  The plug-in is working fine to restrict content for "Member" and "Board Members" with each Restriction Title needed to log-in separately for each page.

A "Board Member" needs to log-in to view "KLA Documents".  I would also like the "Board Member" view the "Members" page but adding the content (screenshot) does not seem to work.  That is, the "Members" page can only be viewed by logging-in as a member.

I also attached a screenshot of the Restrictions and Restriction Editor. Please let me know what I'm doing wrong.
Many thanks
Ken
![Restrictions](https://user-images.githubusercontent.com/75756002/101683507-02d21e80-3a33-11eb-9485-69e34140178d.jpg)
![Restriction Editor](https://user-images.githubusercontent.com/75756002/101683540-0d8cb380-3a33-11eb-8f75-ab5bf9c72e52.jpg)

**Comment by tranKILL** [comment]
I think you have to use OR, not AND

**Comment by danieliser** [comment]
@tranKILL is correct. closing as this is technically a setup issue, though I can understand the confusion.
