### ISSUE TITLE
No more then 10 categories can be selected

### ISSUE THREAD

**Issue by rstauber24** [code-atlantic/content-control#40]
Hello Team

I would like to protect acess to my post according to their category. I have 25 categories. However I can only select the first 10 categories (those that come first in the alphabet) . The other categories do not even show up in the listbox to select them.

**Comment by danieliser** [comment]
@rstauber24 Just patched it, will be in the next update. Was due to us not overloading the default WP query arguments which limits query results to 10 🤦‍♂️.
