### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by Andrewmperryman** [code-atlantic/content-control#47]
![Screenshot 2021-09-14 at 11 07 50](https://user-images.githubusercontent.com/25984766/133230159-55209cbb-dcab-4814-9d01-357f72954f37.png)

**Comment by Andrewmperryman** [comment]
Hello,

Just trialing this great plugin..

I wanted to let you know that query Monitor was throwing up 1 x PHP error as per attached screenshot.

My system info for reference is also below..



`
### WordPress Environment ###

WordPress address (URL): https://revamp-atelier.fr
Site address (URL): https://revamp-atelier.fr
WC Version: 5.6.0
REST API Version: ✔ 5.6.0
WC Blocks Version: ✔ 5.5.1
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.5.1
Log Directory Writable: ✔
WP Version: 5.8.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.23
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1l-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.6.0
WC Database Prefix: chb_
Total Database Size: 14.61MB
Database Data Size: 11.20MB
Database Index Size: 3.41MB
chb_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
chb_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
chb_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
chb_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
chb_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_actionscheduler_actions: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
chb_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_actionscheduler_logs: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
chb_aioseo_notifications: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
chb_aioseo_posts: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
chb_b2s_posts: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
chb_b2s_posts_drafts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_b2s_posts_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_b2s_posts_network_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_b2s_posts_sched_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_b2s_user: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
chb_b2s_user_contact: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_b2s_user_network_settings: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
chb_FinalTiles_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_FinalTiles_gallery_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_gdpr_cc_consentlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_gdpr_cc_geoip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_gdpr_cc_options: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
chb_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
chb_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_lpc_inward_label: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
chb_lpc_outward_label: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_options: Data: 3.48MB + Index: 0.14MB + Engine InnoDB
chb_postmeta: Data: 1.52MB + Index: 0.27MB + Engine InnoDB
chb_posts: Data: 2.42MB + Index: 0.06MB + Engine InnoDB
chb_sgs_log_events: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
chb_sgs_log_visitors: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
chb_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
chb_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
chb_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_trp_dictionary_en_gb_fr_fr: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
chb_trp_gettext_en_gb: Data: 0.31MB + Index: 0.38MB + Engine InnoDB
chb_trp_gettext_fr_fr: Data: 0.23MB + Index: 0.22MB + Engine InnoDB
chb_trp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
chb_trp_original_strings: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
chb_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
chb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
chb_wcfm_membership_subscription: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
chb_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
chb_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
chb_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
chb_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
chb_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
chb_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
chb_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

addify_quote: 1
addify_rfq: 1
addify_rfq_fields: 9
attachment: 224
bwg_gallery: 1
bwg_share: 1
contx_post_type: 8
custom_css: 1
customize_changeset: 52
envira: 1
foogallery: 1
frm_form_actions: 2
frm_styles: 1
language_switcher: 3
mailpoet_page: 1
modula-gallery: 7
nav_menu_item: 9
nimble_post_type: 7
nimble_section: 10
nimble_template: 1
oembed_cache: 3
page: 15
polylang_mo: 2
post: 19
product: 24
revision: 61
shop_order: 14
wp_block: 1
wpape_gallery_theme: 1
wpape_gallery_type: 6
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Query Monitor: by John Blackbourn – 3.7.1
Advanced noCaptcha & invisible Captcha: by Shamim Hasan – 6.1.5
Content Control: by Code Atlantic – 1.1.8
GDPR Cookie Compliance - Premium Add-On: by Moove Agency – 3.0.8
GDPR Cookie Compliance (CCPA, PIPEDA ready): by Moove Agency – 4.5.9
GDPR Data Request Form: by audrasjb – 1.5
GTranslate: by Translate AI Multilingual Solutions – 2.9.2
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Modula: by WPChill – 2.5.3
Nimble Builder Pro: by Press Customizr – 1.0.14
Nimble Page Builder: by Press Customizr – 3.1.21
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
revamp-atelier-change-email-displayname: by Andrew Perryman – 1.0
revamp-atelier-moove-gdpr-cookie: by Andrew Perryman – 1.0
revamp-atelier-woocommerce: by Andrew Perryman – 1.4
revamp-atelier-yith-request-a-quote: by Andrew Perryman – 1.0
SiteGround Optimizer: by SiteGround – 5.9.6
SiteGround Security: by SiteGround – 1.1.2
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.3.13
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.2
WooCommerce PayPal Payments: by WooCommerce – 1.5.1
WooCommerce: by Automattic – 5.6.0
WP Crontrol: by John Blackbourn & contributors – 1.10.0
YITH WooCommerce Request A Quote Premium: by YITH – 3.1.7

### Inactive Plugins (9) ###

Ajax Cart AutoUpdate for WooCommerce: by taisho – 1.5.5
All in One SEO: by All in One SEO Team – 4.1.4.2
Blog2Social: Social Media Auto Post & Scheduler: by Blog2Social
Adenion – 6.8.2

Duplicate Page: by mndpsingh287 – 4.4.3
Page scroll to id: by malihu – 1.7.4
Post Types Order: by Nsp Code – 1.9.5.6
revamp-atelier Maintenance Mode: by Andrew Perryman – 1.0
Widget Disable: by required – 2.0.0
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.12


### Dropin Plugins (2) ###

db.php: Query Monitor Database Class
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4068 - /shop/
Basket: #4069 - /basket/
Checkout: #5284 - /checkout/
My account: #4071 - /my-account/
Terms and conditions: #4171 - /terms-and-conditions-cgv/

### Theme ###

Name: huemanchild
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Hueman Pro
Parent Theme Version: 1.4.15
Parent Theme Author URL: http://presscustomizr.com
WooCommerce Support: ✔

### Templates ###

Overrides: huemanchild/woocommerce/checkout/form-login.php

### WooCommerce PayPal Payments ###

Onboarded: Yes
Shop country code: FR
PayPal card processing available in country: Yes
Pay Later messaging available in country: Yes
Vault enabled: Yes

### Action Scheduler ###

Complete: 482
Oldest: 2021-08-16 12:22:30 +0200
Newest: 2021-09-14 10:41:36 +0200

Pending: 2
Oldest: 2021-09-15 02:35:24 +0200
Newest: 2021-09-15 02:35:24 +0200


### Status report information ###

Generated at: 2021-09-14 10:59:44 +02:00
`

**Comment by Andrewmperryman** [comment]
PS, this maybe nothing but just thought I would give you the heads up, it happens when you "preview changes" to a product in the admin panel WooCommerce\product\ edit section..

Tis all.. Wonderful plugin.. I will donate to show appreciation, once I have tested fully..

**Comment by marklchaves** [comment]
Hey @Andrewmperryman,

We'll look into this. Appreciate all the details 😄 

Cheers!

Mark

**Comment by danieliser** [comment]
Fixed in f80adef07b422bdb2f91091a5bd564a6daccf4e6
