### ISSUE TITLE
Can't edit restriction when LA-Studio Core plugin is active

### ISSUE THREAD

**Issue by NCS-Thomas** [code-atlantic/content-control#48]
I came a rather strange issue today.

WordPress: 5.8.1
Content Control: 1.1.8
LA Studio Core: 2.1.5.2
 
1. Set up a restriction.
2. Click on the edit link: everything works fine.
3. Install plugin LA Studio Core and activate it.
4. Go back to restrictions and click on the edit link: nothing happens.
5. [Optional] Deactivate LA Studio Core plugin.
6. [Optional] Go back to restrictions and click on the edit link: everything works as expected.

Output in console, when clicking on the edit link with LA Studio Core activated:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'restrictions')
    at Object.edit (settings-page.min.js?ver=1.1.8:4)
    at HTMLButtonElement.<anonymous> (settings-page.min.js?ver=1.1.8:4)
    at HTMLDocument.dispatch (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.8.1:2)
    at HTMLDocument.v.handle (load-scripts.php?c=0&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.8.1:2)
```

From the Sources tab:
![prettyfied-js](https://user-images.githubusercontent.com/19685243/134521042-c100314e-ef0e-4115-8a77-08c1752bcc70.png)

The simple work around is to disable LA Studio Core when setting up Content Control.

Kind regards,
Thomas

**Comment by danieliser** [comment]
@NCS-Thomas Sorry for not getting back to you sooner. That said in the time since we have rewritten the plugin entirely. Might be worth retesting to see if this is still an issue or not. Our JS is not handled the same any more which may alleviate the issue.
