### ISSUE TITLE
Prevent short-circuiting of restrictions

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#49]
## Feature request

Potentially add a filter to disable the short-circuiting logic for restrictions. This allows the checking of all restrictions to see if there's an allowable restriction further down the list.

Disabling short-circuiting supports a business requirement where one restriction can have only one role (1:1).

### Example

1. **Restriction 1** allows only the **Tester** role to view posts that have the **Test** category.
2. **Restriction 2** allows only the **Editor** role to view posts that have the **Article** category.

### Current behavior

If there's a post that has the categories **Test** and **Article**, editors won't have permission to view it because **Restriction 1** has priority and the current logic will stop at the first matching restriction.

### Desired behavior

It'd be great to disable the default short-circuiting behavior so that editors can access posts that have both **Test** and **Article** categories assigned.

---

## Reference

See the OP https://wordpress.org/support/topic/prevent-short-circuiting-of-rules/

**Comment by danieliser** [comment]
Based on his original complaint, this new v2 should allow him to do what he wants, it properly checks now any/matching/excluding a bit more explicitly than before.
