### ISSUE TITLE
Fatal error and Deprecated code

### ISSUE THREAD

**Issue by Kuzovlev-Sanya** [code-atlantic/content-control#5]
Deprecated: Non-static method JP\CC\Shortcodes::normalize_empty_atts() should not be called statically in …/plugins/content-control/classes/Shortcodes.php on line 38

Fatal error: Uncaught Error: [] operator not supported for strings in …/plugins/content-control/classes/Shortcodes.php:46 Stack trace: #0 …/wp-includes/shortcodes.php(345): JP\CC\Shortcodes::content_control(Array, ‘Logged in …/plugins/content-control/classes/Shortcodes.php on line 46

**Comment by danieliser** [comment]
These were patched in v1.0.1
