### ISSUE TITLE
How to use programmatically

### ISSUE THREAD

**Issue by creativepartnership** [code-atlantic/content-control#51]
How is it possible to know programmatically if a post (or page) is allowed or forbidden?
Is there a method i can call to know if the post (or page) can be accessed by the current user?
Thanks in advance!

**Comment by danieliser** [comment]
@creativepartnership - It was a long delay, sorry for that, but v2 has been completely redesigned and there are available helper functions for both manually checking your own params, or checking programatically if a specific restriction should apply to the given user.

Beta out later this week.
