### ISSUE TITLE
Hiding Widgets Does Not Work (WordPress 5.8.2)

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#52]
See the original post on .org

https://wordpress.org/support/topic/widget-who-can-see-not-working/

## Steps to reproduce

1. Activate Content Control
2. Edit a widget (**Appearance** > **Widgets**)
3. Restrict access to a logged-in administrator
4. Save
5. Reload the **Widgets** page

The settings changed in step 3 don’t save. So, the widget is still visible to everyone.

I’m not seeing any errors in the browser console or in the Query Monitor plugin.

## Versions

Content Control 1.1.9

WordPress 5.8.2

PHP 7.4.1

**Comment by danieliser** [comment]
This isn't still an issue in v2 @marklchaves is it?

**Comment by mustafaslk** [comment]
@danieliser This problem is still ongoing. FYI

**Comment by marklchaves** [comment]
> This isn't still an issue in v2 @marklchaves is it?

Fully supported and documented in v2. 

https://contentcontrolplugin.com/docs/block-controls/how-to-restrict-widgets/

Works like a charm. Thank you!
