### ISSUE TITLE
Add support for an excerpt filter hook

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#54]
Content Control uses its own excerpt function. So, the built-in WordPress [the_excerpt](https://developer.wordpress.org/reference/hooks/the_excerpt/) hook doesn't work.

It would be great if Content Controls has an excerpt hook to preserve that functionality.

See the [OP on the forum](https://wordpress.org/support/topic/hook-into-excerpt/).

**Comment by danieliser** [comment]
In v2 there are a couple filters for this for each different context, so `'content_control/post_restricted_excerpt'` for example
