### ISSUE TITLE
Possible namespace conflict with serializeObject()

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#55]
Right now, if `$.fn.serializeObject` is defined in another script or plugin while Content Control is running, Content Control throws a JS error and you can't edit a restriction. 

Original post: https://wordpress.org/support/topic/compatibility-issue-with-responsive-for-wpbakery/

Responsive for WPBakery Page Builder: https://codecanyon.net/item/responsive-for-visual-composer/20085272

Content Control version: 1.1.9

Link to the source file: https://github.com/JunglePlugins/Content-Control/blob/master/assets/scripts/settings-page.js

---

You can also inject JS to redefine `serializeObject()` outside of Content Control to generate an error. Here's an example snippet.

```javascript
$.fn.serializeObject = function () {
  console.log("[DEBUG] serializeObject test");
};
```

One possible workaround for a quick fix is to do a global rename on the `serializeObject` function in `settings-page.js` and reminify.

**Comment by danieliser** [comment]
No longer an issue in v2
