### ISSUE TITLE
If a page is restricted to only "logged out" users, admins are not able to edit it with Elementor (feature request(s))

### ISSUE THREAD

**Issue by dani3l3** [code-atlantic/content-control#59]
Hi there, 
a small issue (I think at this stage this behaviour is by design, so I consider this a feature request) : if I configure a page to be only visible to 'logged OUT users', and redirect logged in users elsewhere, this breaks Elementor. I don't have a stack trace but it's very easy to reproduce consistently.

This is not blocking me (for these pages, as a workaround, I am using custom code in a custom plugin that won't trigger if the user is 'admin' or 'editor'...), but it would be nice to have a setting to control the roles/users the rule applies to, in addition to the criteria for choosing the content to restrict. I see a similar setting is present for 'logged IN users', but I would need the opposite.

Many thanks, the plugin is otherwise very nice/clean/small and useful and I gave it a 5-stars review.

An additional nice to have feature request would be the ability to CLONE rules.

With best regads,

**Comment by marklchaves** [comment]
Hey @dani3l3,

Thanks for your feedback and for taking the time to review the plugin ☺️ 

We're sorry for the inconvenience. We're glad you found a workaround. 

For anyone else, there's also a CC filter you can use when Elementor's live preview mode is on. Here's a gist of that.

https://gist.github.com/marklchaves/06d416aa9e9e8d8f44e62301367e9f6d

We'll post any progress updates on this thread.

Cheers!

**Comment by danieliser** [comment]
@dani3l3 I believe we may have done what you were after in v2. There is now a selector for "any", "matching", or "excluding" the selected roles. Letting you do inverse selections etc.

Should be in beta later this week.

Further will add some checks to not restrict content on elementor builder.
