### ISSUE TITLE
Unwanted character encoding when overriding the custom message

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#60]
Content Control does unwanted (named) character encoding when overriding the custom message.

Right now, the workaround is to hit the **Save Changes** button on the Content Control **Settings** page before that page reloads.

Original post: https://wordpress.org/support/topic/errors-when-using-html-in-protection-text-area/

Demo of the issue and workaround: https://share.wppopupmaker.com/geudnGR1

**Comment by danieliser** [comment]
@marklchaves - Can you retest this with v2.0.9, don't think it should be an issue any more. Reopen if it is.

**Comment by marklchaves** [comment]
Hi @danieliser ,

Confirmed. Not an issue in v2.0.9. Thank you 😌 

![fancy-custom-protection-settings](https://github.com/code-atlantic/content-control/assets/4658423/56036b20-7a8d-42e5-859e-097b9236c5ae)

![fancy-custom-html](https://github.com/code-atlantic/content-control/assets/4658423/e7027719-a97a-410b-b7dd-fa5c6facac9d)

![fancy-custom-css](https://github.com/code-atlantic/content-control/assets/4658423/03c4035e-fa9b-4c3d-82ae-deedd6adb7f3)
