### ISSUE TITLE
Default Content Condition Is A Post Doesn't Take Effect

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#61]
## OP

https://wordpress.org/support/topic/basics-are-not-working/

## Workaround

- Change the default **Is A Post** selection to something else. 
- Then, switch it back to **Is A Post** and save your change.

## Demo

https://share.wppopupmaker.com/NQuNv5yz

**Comment by danieliser** [comment]
No longer an issue as it doesn't show that by default
