### ISSUE TITLE
Custom Message doesn't seem to support links

### ISSUE THREAD

**Issue by beryllium** [code-atlantic/content-control#63]
When creating a custom message, I attempted to insert some links into the content in order to direct users to the Login page or a recruiting page.

The URLs ended up being encoded with quotes as part of the string, so the browser attempted to go to (for example) `https://example.com/"/wp/wp-login.php"` and `https://example.com/"https://example.com/wp/wp-login.php"`

This was on plugin version 1.1.9.

Aside from that, I've been happy with the plugin so far. Thank you for making it :)

**Comment by iwasthesword** [comment]
I have the same problem, but when adding custom style/classes to the custom message. Any way to prevent the quotes escaping?

**Comment by danieliser** [comment]
v2.0 was a complete rewrite, for that reason I'm closing this for now.

@beryllium  If you see issues in the latest version you should be able to reopen this and ping me, but I don't believe it is.
