### ISSUE TITLE
Shortcode logged_out="0" shows restricted content when logged out and denies restricted content when logged in (as correct role)

### ISSUE THREAD

**Issue by marklchaves** [code-atlantic/content-control#65]
**Original post**: https://wordpress.org/support/topic/making-shortcodes-work-error-in-documentation/

**Reprex demo**: https://share.wppopupmaker.com/6quzk5px

## Short term fix

We can change the README to instruct people to leave out the `logged_out` parameter when allowing only logged-in visitors to view the restricted content. That's because the default kicks in and works fine. Also `logged_out="1"` seems to work well.

**Comment by danieliser** [comment]
@marklchaves - In v2 it has the following code for this deprecated argument, I think it should handle this fine, thoughts? Specifically casting it as `(bool)` in the end forces 0 to be false and 1 to be true.

		// Handle old args.
		if ( null === $atts['status'] && isset( $atts['logged_out]'] ) && (bool) $atts['logged_out'] ) {
			// @deprecated 2.0.0
			$atts['status'] = 'logged_out';
			unset( $atts['logged_out'] );
		}

**Comment by danieliser** [comment]
I think we resolved this fully in v2.0.0 @marklchaves
