### ISSUE TITLE
Not protecting PDF's???

### ISSUE THREAD

**Issue by fusioncw** [code-atlantic/content-control#68]
Using this plugin successfully to protect pages and posts. But since a recent update its no longer protecting PDF files. Running the latest version of WP, Divi Theme, integrated with Wild Apricot. Disabled plugins and tried a default theme and issue persists.

**Comment by danieliser** [comment]
@fusioncw - sorry for the delay, that said this plugin didn't ever protect files on the server. That feature might be there in the future, but its proven to be a very complex endeavor to implement as every sites server is slightly different, writing code for one may not work at all on others.

There are quite a few tickets and even a few negative reviews over this subject already from the past as well that outline further what it really takes to do this.

It is on our list for the future though, we have major stuff in the works already with v2.0 being a complete rewrite.
