### ISSUE TITLE
the popup moves and page don't scroll

### ISSUE THREAD

**Issue by Quit4944** [code-atlantic/content-control#71]
When I go to Restriction Editor -> Content and add a condition with "+AND" (but maybe it happens with other cases too), the popup moves and the scroll is fixed.
It usually happens when I add 3 or more conditions.
I'm using Chrome/Wordpress 6.1.1/Windows 10 all in latest version.

I use the Display zoom at 150%, but the problem is also with 100% (on Start > Settings > System > Display: zoom 100%, 125%, 150%, 175%).
I attach 2 photos to understand.

<img width="960" alt="A" src="https://user-images.githubusercontent.com/125264725/218437669-2c6d4867-9535-4699-acb3-edf19a443440.png">

<img width="960" alt="B" src="https://user-images.githubusercontent.com/125264725/218437676-d678ce6d-52a4-4379-b83c-2a4a892d95ab.png">

**Comment by danieliser** [comment]
@Quit4944 - Apologies for not responding sooner. To be honest we are probably only a week away from releasing v2 which is a complete rewrite of all those interfaces. I am not able to duplicate this on the new version either, so gonna go ahead and mark this as closed.

I invite you to test the beta when its available later this week.
