### ISSUE TITLE
Fatal error when empty shortcode used due to empty $atts value.

### ISSUE THREAD

**Issue by danieliser** [code-atlantic/content-control#9]
It appears that when no attributes are passed, $atts can be a string which when converted to an array is just a letter for each key.

Add a check for `is_array` prior to the foreach.

```[content_control]Hello[/content_control]```

```
Uncaught Error
: Cannot unset string offsets in
/var/www/html/wp-content/plugins/content-control/classes/Shortcodes.php
on line
72
normalize_empty_atts()
wp-content/plugins/content-control/classes/Shortcodes.php:38
content_control()
wp-includes/shortcodes.php:325
do_shortcode_tag()
preg_replace_callback()
wp-includes/shortcodes.php:199```

**Comment by apptv** [comment]
This is critical, because the site will not render any more.

> Got error 'PHP message: PHP Warning:  Illegal string offset '' in /wp-content/plugins/content-control/classes/Shortcodes.php on line 71
> PHP message: PHP Fatal error:  Uncaught Error: Cannot unset string offsets in /wp-content/plugins/content-control/classes/Shortcodes.php:72
> Stack trace:
> #0 /wp-content/plugins/content-control/classes/Shortcodes.php(38): JP\\CC\\Shortcodes::normalize_empty_atts('1')
> #1 /wp-includes/shortcodes.php(325): JP\\CC\\Shortcodes::content_control('', '', 'content_control')
> #2 [internal function]: do_shortcode_tag(Array)

As a workaround if have added a placeholder attribute to the tag.
e.g.: [content_control logged_in]

This will fix the problem.

**Comment by danieliser** [comment]
@apptv Appreciate the tip, patch is coming, unfortunately we have been traveling back from WCUS the past few days and are just starting to get caught up. I hope to push it out later tonight.
